version: "3"
services:
  ist:
    restart: always
    build: ./ist/
    container_name: ist
    volumes:
      - ./ist/:/opt/app/code/ist
      - ./ist/static:/opt/app/code/ist/static
      - ./ist/media:/opt/app/code/ist/media
    
    networks:
      - allinone
  
  est:
    restart: always
    build: ./est/
    container_name: est
    volumes:
      - ./est/:/opt/app/code/est
      - ./est/static:/opt/app/code/est/static
      - ./est/media:/opt/app/code/est/media
    
    networks:
      - allinone

  router:
    restart: always
    image: nginx
    container_name: router
    depends_on:
      - ist
      - est
    

networks:
  allinone:
